import type { FeatureCheck, FeatureCategory } from './types.js'

/**
 * 特性检测项清单
 *
 * 每项 test 是一个 JS 表达式字符串，在目标设备 IIFE 内 try-catch 执行。
 * 求值结果 JSON.stringify 后回传。
 *
 * 分类按诊断场景组织：
 * - css：布局/视觉效果能力（排障"为什么布局坏了"）
 * - js-api：核心 JS API（排障"为什么 API 调用报错"）
 * - network：网络相关能力（排障"为什么请求失败/连不上"）
 * - media：音视频/图形能力（排障"为什么播放不了/渲染异常"）
 * - storage：持久化能力（排障"为什么数据丢了"）
 * - device：设备基础信息（屏幕/触摸/语言等环境诊断）
 * - element：HTML 元素/属性支持（排障"为什么某标签/属性不生效"）
 *
 * 每项 mdn 是 MDN 文档 slug（拼接成 https://developer.mozilla.org/zh-CN/docs/<slug>）
 * 每项 desc 是一句话中文说明，hover 时提示
 */
export const FEATURE_CHECKS: Array<FeatureCheck & { category: FeatureCategory }> = [
  // ────────────────── CSS ──────────────────
  {
    id: 'css.grid',
    label: 'CSS Grid',
    category: 'css',
    test: `CSS.supports('display', 'grid')`,
    mdn: 'Web/CSS/CSS_grid_layout',
    desc: '二维网格布局系统，适合复杂页面布局',
  },
  {
    id: 'css.flexbox',
    label: 'Flexbox',
    category: 'css',
    test: `CSS.supports('display', 'flex')`,
    mdn: 'Web/CSS/CSS_flexible_box_layout',
    desc: '一维弹性布局，适合组件内对齐和分布',
  },
  {
    id: 'css.subgrid',
    label: 'CSS Subgrid',
    category: 'css',
    test: `CSS.supports('grid-template-columns', 'subgrid')`,
    mdn: 'Web/CSS/CSS_grid_layout/Subgrid',
    desc: '子网格继承父网格的轨道定义，实现嵌套对齐',
  },
  {
    id: 'css.sticky',
    label: 'position: sticky',
    category: 'css',
    test: `CSS.supports('position', 'sticky')`,
    mdn: 'Web/CSS/position',
    desc: '滚动到阈值时固定在视口，常见于吸顶导航',
  },
  {
    id: 'css.gap',
    label: 'CSS gap（flex）',
    category: 'css',
    test: `CSS.supports('gap', '1px')`,
    mdn: 'Web/CSS/gap',
    desc: 'flex/grid 布局中行和列之间的间距',
  },
  {
    id: 'css.aspect-ratio',
    label: 'aspect-ratio',
    category: 'css',
    test: `CSS.supports('aspect-ratio', '16 / 9')`,
    mdn: 'Web/CSS/aspect-ratio',
    desc: 'CSS 原生控制元素宽高比，无需 padding hack',
  },
  {
    id: 'css.container-queries',
    label: 'Container Queries',
    category: 'css',
    test: `CSS.supports('container-type', 'inline-size')`,
    mdn: 'Web/CSS/CSS_container_queries',
    desc: '基于父容器尺寸（而非视口）响应式调整样式',
  },
  {
    id: 'css.backdrop-filter',
    label: 'backdrop-filter',
    category: 'css',
    test: `CSS.supports('backdrop-filter', 'blur(1px)') || CSS.supports('-webkit-backdrop-filter', 'blur(1px)')`,
    mdn: 'Web/CSS/backdrop-filter',
    desc: '毛玻璃/磨砂效果，对元素背后的区域应用滤镜',
  },
  {
    id: 'css.oklch',
    label: 'oklch() 颜色',
    category: 'css',
    test: `CSS.supports('color', 'oklch(0.5 0.1 180)')`,
    mdn: 'Web/CSS/color_value/oklch',
    desc: '感知均匀的色彩空间，比 RGB/HSL 更符合人眼',
  },
  {
    id: 'css.color-mix',
    label: 'color-mix()',
    category: 'css',
    test: `CSS.supports('color', 'color-mix(in srgb, red, blue)')`,
    mdn: 'Web/CSS/color_value/color-mix',
    desc: '在 CSS 中混合两种颜色，无需预计算',
  },
  {
    id: 'css.scroll-driven',
    label: 'Scroll-Driven Animations',
    category: 'css',
    test: `'animate' in document && CSS.supports('animation-timeline', 'scroll()')`,
    mdn: 'Web/CSS/animation-timeline',
    desc: '滚动进度驱动的 CSS 动画，无需 JS 监听滚动',
  },
  {
    id: 'css.custom-properties',
    label: 'CSS Custom Properties (变量)',
    category: 'css',
    test: `CSS.supports('--x', '0')`,
    mdn: 'Web/CSS/--*',
    desc: 'CSS 自定义属性（变量），运行时可读写',
  },
  {
    id: 'css.focus-visible',
    label: ':focus-visible',
    category: 'css',
    test: `CSS.supports('selector(:focus-visible)')`,
    mdn: 'Web/CSS/:focus-visible',
    desc: '仅在键盘聚焦时显示焦点环，鼠标点击不显示',
  },
  {
    id: 'css.has',
    label: ':has() 父选择器',
    category: 'css',
    test: `CSS.supports('selector(:has(*))')`,
    mdn: 'Web/CSS/:has',
    desc: '根据子元素状态选择父元素（CSS "父选择器"）',
  },
  {
    id: 'css.nesting',
    label: 'CSS Nesting',
    category: 'css',
    test: `CSS.supports('selector(&)')`,
    mdn: 'Web/CSS/CSS_nesting',
    desc: 'CSS 原生嵌套语法，无需预处理器',
  },
  {
    id: 'css.mask',
    label: 'CSS Mask',
    category: 'css',
    test: `CSS.supports('mask-image', 'none') || CSS.supports('-webkit-mask-image', 'none')`,
    mdn: 'Web/CSS/mask-image',
    desc: '用图片裁剪元素可见区域，实现复杂形状',
  },
  {
    id: 'css.border-image',
    label: 'border-image',
    category: 'css',
    test: `CSS.supports('border-image-source', 'none')`,
    mdn: 'Web/CSS/border-image',
    desc: '用图片绘制边框，替代简单 border 样式',
  },

  // ────────────────── JS API ──────────────────
  {
    id: 'js.optional-chaining',
    label: 'Optional Chaining (?.)',
    category: 'js-api',
    test: `(function(){ try { eval('({})?.a') } catch(e) { return false } return true })()`,
    mdn: 'Web/JavaScript/Reference/Operators/Optional_chaining',
    desc: '安全访问深层属性，中间为 null/undefined 不报错',
  },
  {
    id: 'js.nullish-coalescing',
    label: 'Nullish Coalescing (??)',
    category: 'js-api',
    test: `(function(){ try { eval('null ?? 1') } catch(e) { return false } return true })()`,
    mdn: 'Web/JavaScript/Reference/Operators/Nullish_coalescing',
    desc: '仅 null/undefined 时取默认值（区别于 || 的 falsy）',
  },
  {
    id: 'js.structured-clone',
    label: 'structuredClone()',
    category: 'js-api',
    test: `typeof structuredClone === 'function'`,
    mdn: 'Web/API/structuredClone',
    desc: '深拷贝对象（含 Date/Map/Set 等），替代 JSON hack',
  },
  {
    id: 'js.intersection-observer',
    label: 'IntersectionObserver',
    category: 'js-api',
    test: `'IntersectionObserver' in window`,
    mdn: 'Web/API/IntersectionObserver',
    desc: '高效检测元素是否进入视口，用于懒加载/曝光统计',
  },
  {
    id: 'js.mutation-observer',
    label: 'MutationObserver',
    category: 'js-api',
    test: `'MutationObserver' in window`,
    mdn: 'Web/API/MutationObserver',
    desc: '监听 DOM 变化（增删节点/属性修改）',
  },
  {
    id: 'js.resize-observer',
    label: 'ResizeObserver',
    category: 'js-api',
    test: `'ResizeObserver' in window`,
    mdn: 'Web/API/ResizeObserver',
    desc: '监听元素尺寸变化，替代 window.resize 方案',
  },
  {
    id: 'js.performance-observer',
    label: 'PerformanceObserver',
    category: 'js-api',
    test: `'PerformanceObserver' in window`,
    mdn: 'Web/API/PerformanceObserver',
    desc: '监听性能指标（LCP/CLS/FCP 等 Core Web Vitals）',
  },
  {
    id: 'js.web-components',
    label: 'Custom Elements + Shadow DOM',
    category: 'js-api',
    test: `'customElements' in window && 'attachShadow' in Element.prototype`,
    mdn: 'Web/API/Web_components',
    desc: '原生组件化方案，自定义元素 + 样式隔离的 Shadow DOM',
  },
  {
    id: 'js.crypto',
    label: 'Web Crypto (crypto.subtle)',
    category: 'js-api',
    test: `'subtle' in crypto`,
    mdn: 'Web/API/Crypto/subtle',
    desc: '原生加密 API（SHA/AES/RSA 等），替代 JS 加密库',
  },
  {
    id: 'js.share',
    label: 'navigator.share',
    category: 'js-api',
    test: `'share' in navigator`,
    mdn: 'Web/API/Navigator/share',
    desc: '调用系统原生分享面板（移动端为主）',
  },
  {
    id: 'js.clipboard',
    label: 'Clipboard API',
    category: 'js-api',
    test: `'clipboard' in navigator && 'writeText' in navigator.clipboard`,
    mdn: 'Web/API/Clipboard_API',
    desc: '异步读写剪贴板，替代 document.execCommand',
  },
  {
    id: 'js.service-worker',
    label: 'Service Worker',
    category: 'js-api',
    test: `'serviceWorker' in navigator`,
    mdn: 'Web/API/Service_Worker_API',
    desc: '离线缓存/后台同步/推送通知的基础，PWA 核心',
  },
  {
    id: 'js.web-worker',
    label: 'Web Worker',
    category: 'js-api',
    test: `'Worker' in window`,
    mdn: 'Web/API/Web_Workers_API',
    desc: '后台线程执行 JS，不阻塞主线程 UI',
  },
  {
    id: 'js.shared-array-buffer',
    label: 'SharedArrayBuffer',
    category: 'js-api',
    test: `'SharedArrayBuffer' in window`,
    mdn: 'Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer',
    desc: '跨 Worker 共享内存（需 COOP/COEP 安全头）',
  },
  {
    id: 'js.importmap',
    label: 'Import Maps',
    category: 'js-api',
    test: `HTMLScriptElement.supports && HTMLScriptElement.supports('importmap')`,
    mdn: 'Web/HTML/Element/script/type/importmap',
    desc: '浏览器原生 bare module 映射，无需打包工具',
  },
  {
    id: 'js.text-encoder',
    label: 'TextEncoder & TextDecoder',
    category: 'js-api',
    test: `'TextEncoder' in window && 'TextDecoder' in window`,
    mdn: 'Web/API/TextEncoder',
    desc: '字符串与 Uint8Array 互转，处理二进制数据的基础',
  },
  {
    id: 'js.typed-arrays',
    label: 'Typed Arrays (Uint8Array)',
    category: 'js-api',
    test: `'Uint8Array' in window`,
    mdn: 'Web/JavaScript/Reference/Global_Objects/Typed_arrays',
    desc: '定长二进制数组，操作文件/WebSocket/WebGL 数据',
  },
  {
    id: 'js.url-search-params',
    label: 'URLSearchParams',
    category: 'js-api',
    test: `'URLSearchParams' in window`,
    mdn: 'Web/API/URLSearchParams',
    desc: '解析和构造 URL 查询参数（?a=1&b=2）',
  },
  {
    id: 'js.web-animations',
    label: 'Web Animations API',
    category: 'js-api',
    test: `'animate' in Element.prototype`,
    mdn: 'Web/API/Web_Animations_API',
    desc: '用 JS API（element.animate）驱动动画，替代 CSS',
  },

  // ────────────────── Network ──────────────────
  {
    id: 'net.fetch',
    label: 'Fetch API',
    category: 'network',
    test: `typeof fetch === 'function'`,
    mdn: 'Web/API/Fetch_API',
    desc: '现代 HTTP 请求 API，替代 XMLHttpRequest',
  },
  {
    id: 'net.fetch-streams',
    label: 'Fetch ReadableStream',
    category: 'network',
    test: `typeof fetch === 'function' && typeof ReadableStream !== 'undefined'`,
    mdn: 'Web/API/ReadableStream',
    desc: '流式读取响应体，处理大文件/流式数据',
  },
  {
    id: 'net.websocket',
    label: 'WebSocket',
    category: 'network',
    test: `'WebSocket' in window`,
    mdn: 'Web/API/WebSocket',
    desc: '全双工持久连接，实时通信（聊天/推送/协同）',
  },
  {
    id: 'net.eventsource',
    label: 'EventSource (SSE)',
    category: 'network',
    test: `'EventSource' in window`,
    mdn: 'Web/API/EventSource',
    desc: '服务器单向推送事件流（Server-Sent Events）',
  },
  {
    id: 'net.beacon',
    label: 'navigator.sendBeacon',
    category: 'network',
    test: `'sendBeacon' in navigator`,
    mdn: 'Web/API/Navigator/sendBeacon',
    desc: '页面卸载时可靠上报数据（不阻塞跳转）',
  },
  {
    id: 'net.online',
    label: '当前在线',
    category: 'network',
    test: `navigator.onLine`,
    mdn: 'Web/API/Navigator/onLine',
    desc: '检测网络连接状态（可能误报，仅作参考）',
  },
  {
    id: 'net.connection',
    label: 'Network Information API',
    category: 'network',
    test: `'connection' in navigator || 'mozConnection' in navigator`,
    mdn: 'Web/API/Network_Information_API',
    desc: '获取网络类型/速度（4g/wifi 等），自适应加载',
  },
  {
    id: 'net.cors',
    label: 'CORS',
    category: 'network',
    test: `typeof fetch === 'function' && 'mode' in new Request('')`,
    mdn: 'Web/HTTP/CORS',
    desc: '跨域资源共享，控制浏览器跨域请求',
  },

  // ────────────────── Media ──────────────────
  {
    id: 'media.video',
    label: '<video> 元素',
    category: 'media',
    test: `!!document.createElement('video').canPlayType`,
    mdn: 'Web/API/HTMLVideoElement',
    desc: '原生视频播放能力',
  },
  {
    id: 'media.audio',
    label: '<audio> 元素',
    category: 'media',
    test: `!!document.createElement('audio').canPlayType`,
    mdn: 'Web/API/HTMLAudioElement',
    desc: '原生音频播放能力',
  },
  {
    id: 'media.webcodecs',
    label: 'WebCodecs',
    category: 'media',
    test: `'VideoDecoder' in window`,
    mdn: 'Web/API/WebCodecs_API',
    desc: '底层音视频编解码 API，高性能视频处理',
  },
  {
    id: 'media.mediastream',
    label: 'Media Capture (getUserMedia)',
    category: 'media',
    test: `!!(navigator.mediaDevices && navigator.mediaDevices.getUserMedia)`,
    mdn: 'Web/API/MediaDevices/getUserMedia',
    desc: '访问摄像头/麦克风，WebRTC 基础',
  },
  {
    id: 'media.webaudio',
    label: 'Web Audio API',
    category: 'media',
    test: `'AudioContext' in window || 'webkitAudioContext' in window`,
    mdn: 'Web/API/Web_Audio_API',
    desc: '音频合成/处理/分析，游戏和音乐应用',
  },
  {
    id: 'media.webgl',
    label: 'WebGL',
    category: 'media',
    test: `(function(){ try { return !!document.createElement('canvas').getContext('webgl') } catch(e) { return false } })()`,
    mdn: 'Web/API/WebGL_API',
    desc: '浏览器 3D 图形渲染（Canvas + OpenGL ES）',
  },
  {
    id: 'media.webgl2',
    label: 'WebGL2',
    category: 'media',
    test: `(function(){ try { return !!document.createElement('canvas').getContext('webgl2') } catch(e) { return false } })()`,
    mdn: 'Web/API/WebGL2_API',
    desc: 'WebGL 升级版（3D 纹理/实例化/变换反馈）',
  },
  {
    id: 'media.webrtc',
    label: 'WebRTC',
    category: 'media',
    test: `'RTCPeerConnection' in window`,
    mdn: 'Web/API/WebRTC_API',
    desc: '浏览器间点对点音视频/数据通信',
  },

  // ────────────────── Storage ──────────────────
  {
    id: 'storage.localstorage',
    label: 'localStorage',
    category: 'storage',
    test: `(function(){ try { return 'localStorage' in window && window.localStorage !== null } catch(e) { return false } })()`,
    mdn: 'Web/API/Window/localStorage',
    desc: '永久键值存储（~5-10MB，同步 API）',
  },
  {
    id: 'storage.sessionstorage',
    label: 'sessionStorage',
    category: 'storage',
    test: `(function(){ try { return 'sessionStorage' in window && window.sessionStorage !== null } catch(e) { return false } })()`,
    mdn: 'Web/API/Window/sessionStorage',
    desc: '会话级键值存储，标签关闭即清除',
  },
  {
    id: 'storage.indexeddb',
    label: 'IndexedDB',
    category: 'storage',
    test: `'indexedDB' in window`,
    mdn: 'Web/API/IndexedDB_API',
    desc: '大容量结构化数据存储（异步事务，~数百 MB）',
  },
  {
    id: 'storage.cookies',
    label: 'Cookie',
    category: 'storage',
    test: `'cookie' in document`,
    mdn: 'Web/API/Document/cookie',
    desc: '传统存储，随请求自动携带（~4KB 限制）',
  },
  {
    id: 'storage.cache-api',
    label: 'Cache API',
    category: 'storage',
    test: `'caches' in window`,
    mdn: 'Web/API/Cache',
    desc: 'Service Worker 缓存 Request/Response 对象',
  },

  // ────────────────── Device ──────────────────
  {
    id: 'device.touch',
    label: '触摸屏',
    category: 'device',
    test: `'ontouchstart' in window || navigator.maxTouchPoints > 0`,
    mdn: 'Web/API/Touch_events',
    desc: '设备支持触摸输入',
  },
  {
    id: 'device.pwa-installable',
    label: 'PWA 可安装',
    category: 'device',
    test: `'BeforeInstallPromptEvent' in window`,
    mdn: 'Web/API/BeforeInstallPromptEvent',
    desc: '满足 PWA 安装条件，可提示用户"添加到主屏幕"',
  },
  {
    id: 'device.dark-mode',
    label: 'prefers-color-scheme',
    category: 'device',
    test: `window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'`,
    mdn: 'Web/CSS/@media/prefers-color-scheme',
    desc: '用户系统深色/浅色主题偏好',
  },
  {
    id: 'device.cookie-enabled',
    label: 'Cookie 启用',
    category: 'device',
    test: `navigator.cookieEnabled`,
    mdn: 'Web/API/Navigator/cookieEnabled',
    desc: '浏览器是否启用 Cookie',
  },
  {
    id: 'device.do-not-track',
    label: 'Do Not Track',
    category: 'device',
    test: `navigator.doNotTrack === '1' || navigator.doNotTrack === 'yes'`,
    mdn: 'Web/API/Navigator/doNotTrack',
    desc: '用户请求不被跟踪',
  },

  // ────────────────── Element ──────────────────
  {
    id: 'el.img-lazy',
    label: '<img loading="lazy">',
    category: 'element',
    test: `'loading' in HTMLImageElement.prototype`,
    mdn: 'Web/API/HTMLImageElement/loading',
    desc: '图片原生懒加载，无需 IntersectionObserver',
  },
  {
    id: 'el.img-srcset',
    label: '<img srcset>',
    category: 'element',
    test: `'srcset' in document.createElement('img')`,
    mdn: 'Web/API/HTMLImageElement/srcset',
    desc: '响应式图片，按 DPR/视口自动选最佳分辨率',
  },
  {
    id: 'el.img-webp',
    label: 'WebP 图片格式',
    category: 'element',
    test: `(function(){ var c = document.createElement('canvas'); return c.toDataURL('image/webp').indexOf('data:image/webp') === 0 })()`,
    mdn: 'Web/Media/Formats/Image_types#webp',
    desc: '现代图片格式，比 PNG/JPEG 体积更小',
  },
  {
    id: 'el.script-async',
    label: '<script async>',
    category: 'element',
    test: `'async' in document.createElement('script')`,
    mdn: 'Web/HTML/Element/script',
    desc: '异步加载脚本，不阻塞 HTML 解析',
  },
  {
    id: 'el.script-defer',
    label: '<script defer>',
    category: 'element',
    test: `'defer' in document.createElement('script')`,
    mdn: 'Web/HTML/Element/script',
    desc: '延迟执行脚本，DOM 解析完后按序执行',
  },
  {
    id: 'el.iframe-sandbox',
    label: '<iframe sandbox>',
    category: 'element',
    test: `'sandbox' in document.createElement('iframe')`,
    mdn: 'Web/HTML/Element/iframe',
    desc: '沙箱化 iframe，限制其脚本/表单/导航等能力',
  },
  {
    id: 'el.link-prefetch',
    label: '<link rel="prefetch">',
    category: 'element',
    test: `(function(){ var l = document.createElement('link'); return l.relList && l.relList.supports && l.relList.supports('prefetch') })()`,
    mdn: 'Web/HTTP/Headers/Link',
    desc: '空闲时预取下一页资源，加速导航',
  },
  {
    id: 'el.dialog',
    label: '<dialog> 元素',
    category: 'element',
    test: `'showModal' in document.createElement('dialog')`,
    mdn: 'Web/HTML/Element/dialog',
    desc: '原生模态对话框，自带遮罩和焦点陷阱',
  },
  {
    id: 'el.details',
    label: '<details>/<summary>',
    category: 'element',
    test: `'open' in document.createElement('details')`,
    mdn: 'Web/HTML/Element/details',
    desc: '原生折叠面板，无需 JS 实现展开/收起',
  },
  {
    id: 'el.popover',
    label: 'Popover API',
    category: 'element',
    test: `'showPopover' in HTMLElement.prototype`,
    mdn: 'Web/API/Popover_API',
    desc: '原生弹出层，声明式 popovertarget 触发',
  },
]
